name: Container Build And Upload
description: |
  Builds and uploads to GHCR (GitHub Container Registry) the container used to build the Qualcomm debian packages.
  This workflow will assumes the build architecture is amd64 (x86_64) since the github's 'ubuntu-latest' runs-on tag
  is used. Using docker's buildx, the Dockerfile in this repo's docker/ folder will be built for amd64 and cross-compiled
  for arm64.

on:
  schedule:
    # Runs at 00:00 UTC every Monday
    - cron: '0 0 * * 1'

  pull_request_target:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      version:
        description: The version name to be appended to the image name, default is 'latest'
        type: string
        default: latest

permissions:
  contents: read
  security-events: write

env:
  QCOM_ORG_NAME: "qualcomm-linux"

  IMAGE_NAME: "pkg-builder"

jobs:

  # Check if this PR changes files in the docker/ folder
  check-if-build-needed:
    runs-on: ubuntu-latest
    outputs:
      build-needed: ${{ steps.set-output.outputs.build-needed }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          fetch-depth: 0

      - name: Check if build is needed
        id: set-output
        run: |
          echo "build-needed=true" >> $GITHUB_OUTPUT
          
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
            echo "Changed files: $CHANGED_FILES"
            if [[ $CHANGED_FILES == *"docker/"* ]]; then
              echo "Build IS needed as docker/ folder changed."
              echo "build-needed=true" >> $GITHUB_OUTPUT
            else
              echo "Build is NOT needed as docker/ folder did not change."
              echo "build-needed=false" >> $GITHUB_OUTPUT
            fi
          fi

  build-image-amd64:
    needs: check-if-build-needed
    if: needs.check-if-build-needed.outputs.build-needed == 'true'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Dockerfile
        uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          sparse-checkout: docker

      - name: Build and Tag the Image
        run: docker build -f docker/Dockerfile.amd64 -t ghcr.io/${{env.QCOM_ORG_NAME}}/${{env.IMAGE_NAME}}:amd64-${{inputs.version}} ./docker

      - name: Authenticate to GHCR
        if: github.event_name != 'pull_request_target'
        run: echo ${{ secrets.DEB_PKG_BOT_CI_TOKEN }} | docker login ghcr.io -u ${{ vars.DEB_PKG_BOT_CI_USERNAME }} --password-stdin

      - name: Push
        if: github.event_name != 'pull_request_target'
        run: docker push ghcr.io/${{env.QCOM_ORG_NAME}}/${{env.IMAGE_NAME}}:amd64-${{inputs.version}}

  build-image-arm64:
    needs: check-if-build-needed
    if: needs.check-if-build-needed.outputs.build-needed == 'true'
    runs-on: ["self-hosted", "lecore-prd-u2404-arm64-xlrg-od-ephem"]
    steps:

      - name: Checkout Dockerfile
        uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          sparse-checkout: docker

      - name: Build and Tag the Image
        run: docker build -f docker/Dockerfile.arm64 -t ghcr.io/${{env.QCOM_ORG_NAME}}/${{env.IMAGE_NAME}}:arm64-${{inputs.version}} ./docker

      - name: Authenticate to GHCR
        if: github.event_name != 'pull_request_target'
        run: echo ${{ secrets.DEB_PKG_BOT_CI_TOKEN }} | docker login ghcr.io -u ${{ vars.DEB_PKG_BOT_CI_USERNAME }} --password-stdin

      - name: Push
        if: github.event_name != 'pull_request_target'
        run: docker push ghcr.io/${{env.QCOM_ORG_NAME}}/${{env.IMAGE_NAME}}:arm64-${{inputs.version}}
